"""Add priority_snapshot to RunCase

Revision ID: 07f462fa8a83
Revises: e8323c1b7b0f
Create Date: 2026-01-05 14:45:39.073131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f462fa8a83'
down_revision = 'e8323c1b7b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_cases', sa.Column('priority_snapshot', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_cases', 'priority_snapshot')
    # ### end Alembic commands ###


