"""add_run_summary_fields

Revision ID: 6234e33713d0
Revises: cdeabbfc3a4c
Create Date: 2026-01-05 18:05:26.535958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6234e33713d0'
down_revision = 'cdeabbfc3a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('summary_prompt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'runs', 'summary_prompts', ['summary_prompt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_column('runs', 'summary_prompt_id')
    op.drop_column('runs', 'summary')
    # ### end Alembic commands ###


