"""Add model field to TranslationPrompt

Revision ID: a5632aa01ff6
Revises: 1fe7d3ba2d6b
Create Date: 2025-12-31 16:44:54.589156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5632aa01ff6'
down_revision = '1fe7d3ba2d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_prompts', sa.Column('model', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_prompts', 'model')
    # ### end Alembic commands ###


