"""Phase 1: Add build_label, bug_links, version, and snapshot fields

Revision ID: e8323c1b7b0f
Revises: a5632aa01ff6
Create Date: 2026-01-05 13:20:20.349501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8323c1b7b0f'
down_revision = 'a5632aa01ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('results', sa.Column('bug_links', sa.Text(), nullable=True))
    op.add_column('run_cases', sa.Column('case_version_snapshot', sa.Integer(), nullable=True))
    op.add_column('run_cases', sa.Column('title_snapshot', sa.String(length=500), nullable=True))
    op.add_column('run_cases', sa.Column('steps_snapshot', sa.Text(), nullable=True))
    op.add_column('run_cases', sa.Column('expected_result_snapshot', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('build_label', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'build_label')
    op.drop_column('run_cases', 'expected_result_snapshot')
    op.drop_column('run_cases', 'steps_snapshot')
    op.drop_column('run_cases', 'title_snapshot')
    op.drop_column('run_cases', 'case_version_snapshot')
    op.drop_column('results', 'bug_links')
    op.drop_column('cases', 'version')
    # ### end Alembic commands ###


